### ISSUE TITLE
Hidden columns throwing off column calculation

### ISSUE THREAD

**Issue by aaronware** [linchpinagency/mesh#14]
This is from kelter in the wordpress.org forums

When switching from a higher column amount to a lower amount (ie, going from 4 to 3) there should be a way to fully delete the content of the column - or likely the column itself? Currently the WP Editor still tries keep <p>
</p> in there, which fools Mesh into thinking I want the content.

Mesh reports back, "The number of columns selected is causing some content to be hidden. Increase the column number to access that content." and then continues to add a column with class="small-12 medium- columns " (note: missing medium #) and thus breaks the layout from the intent.

**Comment by badcat** [comment]
@badcat is kelter on WP forums if you haven't guessed :)
