### ISSUE TITLE
Column selection should not save in real time

### ISSUE THREAD

**Issue by maxinacube** [linchpinagency/mesh#17]
Many of the real time items have been removed in order to use the "update" button. I noticed that the column selection is still doing the active saving.

**Comment by aaronware** [comment]
Going to consider this one partially filed. This needs to be looked at a little more in depth in the future. While the pull request does fix saving of the post meta and how many columns a section has; it does not take into account that a new mesh post is created and held in purgatory. @desrosj any thoughts on this?

My take is that maybe the actual mesh post for a given block will not be created on "add" but instead created on "update". This would solve the problem of the block being created when not needed.

**Comment by desrosj** [comment]
That is exactly what the `auto-draft` status was made for with posts. When you click add new for a post type, an auto draft post is created. When you click save, then the post transitions to draft, publish, etc.. It may stay `auto-draft` when your post content is saved automatically as you type, or it may transition to draft when content is put in. But this seems like the right way to do it.

**Comment by aaronware** [comment]
Considering this one closed
