### ISSUE TITLE
Column "More" Options UI is very tight and overlaps.

### ISSUE THREAD

**Issue by badcat** [linchpinagency/mesh#18]
Perhaps there's probably a cleaner way to solve this overlapping issue with the More Options showing a background image, Column Offset and Classname field?

![mesh-more-columns-ui](https://cloud.githubusercontent.com/assets/26096/15407673/25f0baf4-1dda-11e6-8432-a4edf8302c4b.png)

**Comment by aaronware** [comment]
Rolling out momentarily. Fix from @nate-allen was merged with some updates from @maxinacube .
