### ISSUE TITLE
Missing ability to choose media size after its been added to mesh column

### ISSUE THREAD

**Issue by axion-mike** [linchpinagency/mesh#27]
Adding media is working just great. When you first "Add Media" WordPress gives the ability to choose a size based on the options set in your theme. (Thumbnail, Medium, Full Size).

If we don't specify a size when initially adding the media, the option is not there when editing media inside of a mesh column.

<img width="1017" alt="screen shot 2016-08-09 at 9 29 47 am" src="https://cloud.githubusercontent.com/assets/5727063/17517978/e0902984-5e13-11e6-9188-e1f1de7feea9.png">

**Comment by aaronware** [comment]
I think that may have happened because the image was too small to have multiple sizes?

![Image After select](https://cldup.com/JWiyCzQNa3.png)

**Comment by aaronware** [comment]
The above is a screenshot from 1.1 but nothing has been edited related to media for this next release
