### ISSUE TITLE
When applying a template to a page. The order of is incorrect

### ISSUE THREAD

**Issue by aaronware** [linchpinagency/mesh#43]
When applying a template to a page the order is reversed initially.
Upon page save/publish the order will THEN change to mostly correct but the it places the 1st section last.

EX. 1, 2, 3, 4 within the template.
On creation: 4,3,2,1
On Publish: 2,3,4,1

@maxinacube was able to confirm this but is going to do some more testing

**Comment by aaronware** [comment]
I think this is good to go. Pushed at change to the 1.1.4 branch

**Comment by aaronware** [comment]
@maxinacube when you get a chance can you give it a QA?

**Comment by maxinacube** [comment]
Looks good, no longer seeing this bug!
