### ISSUE TITLE
Performance update for post meta

### ISSUE THREAD

**Issue by aaronware** [linchpinagency/mesh#51]
Query all post meta associated with a section and/or block in order to cut down on how many queries are hitting the database.

**Comment by jcowher** [comment]
@aaronware,

I stepped through `get_post_meta()` and it looks like the core code is already optimized for performance. One database query is made to grab all of the metadata for a given object and then stores the fetched data in cache. Unless there's a reason other than performance, I don't think there's anything we need to do on this.
