### ISSUE TITLE
Make normal editor collapsible

### ISSUE THREAD

**Issue by strarsis** [linchpinagency/mesh#76]
When columns are used immediately, the normal editor is not needed, 
but it can be distracting as it occupies space before the actual Mesh metabox.
Should Mesh make the editor collapsible or an extra plugin instead?

**Comment by aaronware** [comment]
I see where you're coming from but I disagree with manipulating the core editor for this plugin

**Comment by strarsis** [comment]
@aaronware: Are there plugins that offer this functionality?
